### ISSUE TITLE
Stuck at "Starting..."

### ISSUE THREAD

**Issue by prayashm** [berpj/torrent-pizza#4]
I am getting this error in the javascript console:
GET https://api.torrent.pizza/add/713025becf9c414671a76dcc07efb6c3e3a2755b net::ERR_NAME_NOT_RESOLVED

**Comment by berpj** [comment]
Sadly I had to shut it down: https://twitter.com/berpj/status/679314979825160193

Thanks for your message, I'll had a note to the readme!
